# Generated by Django 4.2.3 on 2023-08-05 17:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("students", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentgroup",
            options={
                "ordering": ("name",),
                "verbose_name": "Учебная группа",
                "verbose_name_plural": "Учебные группы",
            },
        ),
        migrations.AlterField(
            model_name="studentgroup",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"user_type": "S"},
                related_name="student_groups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Студенты",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentgroup",
            constraint=models.CheckConstraint(
                check=models.Q(("students__count__lte", 20)),
                name="max_students_per_group",
            ),
        ),
    ]
