# Generated by Django 4.2.3 on 2023-08-05 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("students", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentgroup",
            options={
                "ordering": ("name",),
                "verbose_name": "Учебная группа",
                "verbose_name_plural": "Учебные группы",
            },
        ),
        migrations.AlterField(
            model_name="studentgroup",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.course",
                verbose_name="Направление подготовки",
            ),
        ),
        migrations.AlterField(
            model_name="studentgroup",
            name="curator",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "C"},
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Куратор",
            ),
        ),
        migrations.AlterField(
            model_name="studentgroup",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"user_type": "S"},
                null=True,
                related_name="student_groups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Студенты",
            ),
        ),
    ]
