version: "3.8"

services:
  db:
    image: postgres:15-bullseye
    container_name: metasharks_postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    env_file:
      - ./.env
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
    container_name: metasharks_redis
    command: --port 32768
    ports:
      - "32768:32768"
  web:
    build:
      context: .
    container_name: metasharks_django
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
  celery:
    build:
      context: .
    container_name: metasharks_celery
    command: celery -A metasharks worker --loglevel=INFO
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - redis
      - web
  celery-beat:
    build:
      context: .
    container_name: metasharks_beat
    command: celery -A metasharks beat -l info --scheduler django_celery_beat.schedulers.DatabaseScheduler
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - redis
      - celery
      - web

volumes:
  postgres_data: