# Generated by Django 4.2.3 on 2023-08-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="report",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Отчет",
                "verbose_name_plural": "Отчеты",
            },
        ),
        migrations.AlterField(
            model_name="report",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="reports/", verbose_name="Файл"
            ),
        ),
    ]
